name: Create ToDo

on:
  schedule:
    - cron: "5 3 * * *"
#  push:
#    branches:
#      - master

jobs:
  create_todo:
    name: Create ToDo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create a new issue
        # https://github.com/marketplace/actions/create-an-issue
        uses: JasonEtco/create-an-issue@v2
        with:
          filename: ".github/ISSUE_TEMPLATE/TODO.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
